language: node_js
node_js: 9
os: linux
install:
  - npm install
cache:
  directories:
    - node_modules
jobs:
  include:
  - stage: Check
    script:
    - ./tools/check_signed_off.sh --travis
    - npm run lint-travis
  - stage: Test
    script:
    - npm run test
  - stage: Build
    script:
    - npm run build
